apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-tester"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  activeDeadlineSeconds: 1200
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
      - name: tester
        image: "{{ .Values.testerImage }}"
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_INSTANCE_NAME
          value: {{ .Release.Name }}
      restartPolicy: Never