apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=1GB
    query.max-memory-per-node=512MB
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
  jvm.config: |
    -server
    -Xmx1G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
  node.properties: |
    node.environment=production
    node.id={{ .Release.Name }}
    node.data-dir=/data/trino
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
  password.db: |
    {{ .Values.trino.user }}:{{ .Values.trino.password }}