apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.trino.user | b64enc }}
  password: {{ .Values.trino.password | b64enc }}